import {
  BookOpen,
  BriefcaseBusiness,
  CircleDot,
  Compass,
  GraduationCap,
  Library,
  Map,
  Mic2,
  Users,
  Wrench,
} from "lucide-react";

import type { ModuleCardData } from "@/components/home/ModuleCard";
import { BRAND } from "@/constants/brand";

export const modules: ModuleCardData[] = [
  {
    title: "Bible",
    description: "Read His Word.",
    href: BRAND.routes.bible,
    action: "Open Bible",
    icon: BookOpen,
    accent: "text-blue-300",
    image: "/images/modules/01-bible.jpg",
  },
  {
    title: "Context Circle",
    description: "Study His Word.",
    href: BRAND.routes.contextCircle,
    action: "Open Context Circle",
    icon: CircleDot,
    accent: "text-teal-300",
    image: "/images/modules/02-context-circle.png",
  },
  {
    title: "Research Library",
    description: "Preserve His Word.",
    href: BRAND.routes.library,
    action: "Browse Library",
    icon: Library,
    accent: "text-violet-300",
    image: "/images/modules/03-research-library.png",
  },
  {
    title: "Academy",
    description: "Learn His Word.",
    href: BRAND.routes.academy,
    action: "Go to Academy",
    icon: GraduationCap,
    accent: "text-blue-300",
    image: "/images/modules/04-academy.png",
  },
  {
    title: "Church Curriculum",
    description: "Teach His Word.",
    href: BRAND.routes.churchCurriculum,
    action: "View Curriculum",
    icon: Users,
    accent: "text-green-300",
    image: "/images/modules/05-curriculum.png",
  },
  {
    title: "Doctrine Explorer",
    description: "Defend His Word.",
    href: BRAND.routes.doctrine,
    action: "Explore Doctrine",
    icon: Compass,
    accent: "text-amber-300",
    image: "/images/modules/06-doctrine-explorer.png",
  },
  {
    title: "Bible Atlas",
    description: "Walk His World.",
    href: BRAND.routes.atlas,
    action: "Open Atlas",
    icon: Map,
    accent: "text-cyan-300",
    image: "/images/modules/07-bible-atlas.png",
  },
  {
    title: "Sermons & Outlines",
    description: "Preach His Word.",
    href: BRAND.routes.sermons,
    action: "Browse Messages",
    icon: Mic2,
    accent: "text-purple-300",
    image: "/images/modules/08-sermons.png",
  },
  {
    title: "My Workspace",
    description: "Build with His Word.",
    href: BRAND.routes.workspace,
    action: "Go to Workspace",
    icon: BriefcaseBusiness,
    accent: "text-indigo-300",
    image: "/images/modules/09-workspace.png",
  },
  {
    title: "Tools & Resources",
    description: "Support His Word.",
    href: BRAND.routes.tools,
    action: "Explore Tools",
    icon: Wrench,
    accent: "text-orange-300",
    image: "/images/modules/10-tools.png",
  },
];